# Use the official Node.js image as the base image
FROM node:latest
# Set the working directory in the container
WORKDIR /src/app.jsx

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 8000

CMD ["npm","run","dev"]